config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  match '/users/:id', to: 'users#show', via: 'get', as: 'profile'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get "/about", to: "pages#about", as: :about

  resources "cars", only: [:index, :show, :new, :create, :destroy] do
    collection do
      get :user_cars
    end
    resources "bookings", only: [:create, :index,]
  end

  resources "bookings", only: [:destroy] do
    collection do
      get :user_bookings
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car

  validates :start_date, :end_date, presence: true
  validate :validate_dates

  private

  def validate_dates
    return false unless start_date.present? || end_date.present?

    booking_cannot_be_in_the_past
    end_date_cannot_be_before_start_date
    overlapping_bookings
  end

  def booking_cannot_be_in_the_past
    return unless start_date.past?

    errors.add(:start_date, "cannot be in the past")
  end

  def end_date_cannot_be_before_start_date
    return unless end_date < start_date

    errors.add(:end_date, "must be later than the start date")
  end

  def overlapping_bookings
    new_booking_range = start_date..end_date
    car.bookings.all.each do |booking|
      booking_range = booking.start_date..booking.end_date
      if new_booking_range.overlaps?(booking_range)
        errors.add(:base, "The car is already booked for selected dates")
        errors.add :start_date
        errors.add :end_date
      end
    end
    return
  end
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :renting_users, through: :bookings, source: :user

  validates :model, :brand, :location, :transmission, :day_rate, presence: true

  has_many_attached :photos

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cars, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :booked_cars, through: :bookings, dependent: :destroy, source: :car
  validates :first_name, :last_name, presence: true
  # Removed :email from presence true to re-enable edit my details without
  # changing my password, but still putting in current password.
  validates :email, uniqueness: true
  validates :password, presence: true, on: :create
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :license_number, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :license_number, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
    @car = Car.find(params[:car_id])
    @booked_dates = @car.bookings.pluck(:start_date, :end_date).map { |pair| (pair[0]..pair[1]).to_a }.flatten
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @car = Car.find(params[:car_id])
    @booking.car = @car
    if @booking.save
      @booking = Booking.new
      redirect_to car_path(@car), notice: 'Booking successfully added'
    else
      render 'cars/show', status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    if @booking.destroy
      redirect_to profile_path(current_user), notice: 'Booking successfully cancelled'
    else
      render booking_path(@booking), status: :unprocessable_entity
    end
  end

  def user_bookings
    @bookings = Booking.where(user: current_user)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :user_id, :car_id)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :destroy]

  def index
    @cars = Car.all
    if params[:start_date].present? && params[:end_date].present?
      start_date = params[:start_date].to_date
      end_date = params[:end_date].to_date
      @car_ids = @cars.reject do |car|
        car.bookings.any? do |booking|
          booking_range = booking.start_date..booking.end_date
          booking_range.cover?(start_date.to_date) || booking_range.cover?(end_date.to_date) || (start_date.to_date..end_date.to_date).cover?(booking.start_date) || (start_date.to_date..end_date.to_date).cover?(booking.end_date)
        end
      end.map(&:id)
      @cars = Car.where(id: @car_ids)
    end

    @markers = @cars.geocoded.map do |car|
      {
        lat: car.latitude,
        lng: car.longitude,
        info_window_html: render_to_string(partial: 'info_window', locals: { car: car }),
        marker_html: render_to_string(partial: 'marker', locals: { car: car })
      }
    end
  end

  def show
    @booking = Booking.new
    @booked_dates = @car.bookings.pluck(:start_date, :end_date).map { |pair| (pair[0]..pair[1]).to_a }.flatten
    @daily_rate = @car.day_rate
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    if @car.save
      redirect_to @car, notice: 'Car successfully added'
    else
      render :new, notice: :unprocessable_entity
    end
  end

  def destroy
    if @car.destroy
      redirect_to profile_path(current_user), notice: 'Car succesfully removed'
    end
  end

  def user_cars
    @cars = Car.where(user: current_user)
  end

  private

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:category, :model, :brand, :location, :transmission, :day_rate, :description, :user_id, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@car, booking] do |f| %>
  <% if @booking.errors.any? && @booking.errors.include?(:base) %>
    <p id="error-message"><%= @booking.errors[:base].first %></p>
  <% end %>
  <div data-controller="datepicker"data-datepicker-booked-value="<%= @booked_dates.to_json %>">
    <%= f.input :start_date,
                as: :string,
                label: "Enter chosen dates",
                input_html: { data: { datepicker_target: "start", action: "change->datepicker#update" } } %>

    <%= f.input :end_date,
                as: :hidden,
                input_html: { data: { datepicker_target: "end" } } %>
  </div>
  <%= f.submit %>
<% end %>

app/views/bookings/user_bookings.html.erb
<% if current_user.bookings.any? %>
  <div class="container-fluid mt-3">
    <div class="row g-0">
      <% current_user.bookings.each do |booking| %>
        <div class="col-md-11 mx-auto link-container">
          <%= link_to car_path(booking.car) do %>
            <div class="card mb-3">
              <div class="row g-0">
                <div class="col-md-6">
                  <% carousel_id = "carousel#{booking.id}Indicators" %>
                  <div id="card-image-index">
                    <div id="<%= carousel_id %>" class="carousel slide">
                      <div class="carousel-indicators">
                        <% booking.car.photos.each_with_index do |photo, index| %>
                          <button type="button" data-bs-target="#<%= carousel_id %>" data-bs-slide-to="<%= index %>" class="<%= 'active' if index.zero? %>" aria-label="Slide <%= index + 1 %>"></button>
                        <% end %>
                      </div>
                      <div class="carousel-inner">
                        <% booking.car.photos.each_with_index do |photo, index| %>
                          <div class="carousel-item <%= 'active' if index.zero? %>">
                            <%= image_tag(photo, class: 'd-block w-100', alt: "#{booking.car.brand} #{booking.car.model}") %>
                          </div>
                        <% end %>
                      </div>
                      <button class="carousel-control-prev" type="button" data-bs-target="#<%= carousel_id %>" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                      </button>
                      <button class="carousel-control-next" type="button" data-bs-target="#<%= carousel_id %>" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                      </button>
                    </div>
                  </div>
                </div>
                <div class="pt-2 col-md-3 border-end border-start d-flex flex-column" id="booking-info-index">
                  <h2>Booking Details</h2>
                  <div class= "mt-4 mb-auto">
                    <h5 class="card-title me-2"> <i class="fa-solid fa-calendar"></i> <%= booking.start_date.strftime('%b %d %Y') %> - <%= booking.end_date.strftime('%b %d %Y') %></h5>
                    <h5 class="card-text"> <i class="fa-solid fa-location-dot"></i> <%= booking.car.location %></h5>
                    <h5 class="card-text"> <i class="fa-solid fa-money-bill"></i> Total £<%= ((booking.end_date - booking.start_date) * booking.car.day_rate).round(2)%></h5>
                  </div>
                </div>
                <div class="col-md-3 pt-2 d-flex flex-column" id="car-info-index">
                  <h2>Car Details</h2>
                  <div class="mt-4 mb-auto">
                    <h5 class="card-text"> <i class="fa-solid fa-car"></i></i> <%= booking.car.brand %> <%= booking.car.model %></h5>
                    <h5 class="card-text"> <i class="fa-solid fa-gears"></i> <%= booking.car.transmission %></h5>
                    <h5 class="card-price"> <i class="fa-solid fa-money-bill"></i> £<%= booking.car.day_rate.round() %>/day</h5>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/cars/_car.html.erb
<div class="link-container">
  <%= link_to car_path(car) do %>
  <div class="card">
    <% carousel_id = "carousel#{car.id}Indicators" %>
    <div class="card-image">
      <div id="<%= carousel_id %>" class="carousel slide">
        <div class="carousel-indicators">
          <!-- Card carousel -->
          <% car.photos.each_with_index do |photo, index| %>
            <button type="button" data-bs-target="#<%= carousel_id %>" data-bs-slide-to="<%= index %>" class="<%= 'active' if index.zero? %>" aria-label="Slide <%= index + 1 %>"></button>
          <% end %>
        </div>
        <div class="carousel-inner">
          <% car.photos.each_with_index do |photo, index| %>
            <div class="carousel-item <%= 'active' if index.zero? %>">
              <%= image_tag(photo, class: 'd-block w-100', alt: "#{car.brand} #{car.model}") %>
            </div>
          <% end %>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#<%= carousel_id %>" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#<%= carousel_id %>" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>
    <div class="card-body">
      <!-- Card body content -->
    </div>
    <div class="card-body">
      <div class="card-title d-flex">
        <h2 class="card-title 1 me-2"><%= car.brand %></h2>
        <h2><%= car.model %></h2>
      </div>
      <div class="card-details-1">
        <p class="card-text"> <i class="fa-solid fa-gears"></i> <%= car.transmission %></p>
        <p class="card-text"> <i class="fa-solid fa-location-dot"></i> <%= car.location %></p>
      </div>
      <div class="d-flex justify-content-end">
        <p class="card-price"> £<%= car.day_rate.round() %>/day</p>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/cars/_form.html.erb
<%= simple_form_for [car] do |f| %>
  <%= f.input :model %>
  <%= f.input :brand %>
  <%= f.input :location %>
  <%= f.input :transmission %>
  <%= f.input :day_rate %>
  <%= f.input :description %>
  <%= f.input :photos, input_html: { multiple: true } %>
  <%= f.submit %>
<% end %>

app/views/cars/_info_window.html.erb
<%= link_to car_path(car) do %>
  <%= render partial: 'car', locals: { car: car } %>
<% end %>

app/views/cars/_marker.html.erb
<div class="badge rounded-pill bg-dark fs-6">
  £<%= car.day_rate.round %>
</div>

app/views/cars/_search.html.erb
<%= form_with url: cars_path, method: :get, class: "d-flex" do %>
  <div class="d-flex align-items-center mb-0 me-2">
    <%= label_tag :start_date, "Start Date", class: "form-label mb-0 form-input" %>
    <%= date_field_tag :start_date, params[:start_date], class: "form-control rounded-5" %>
  </div>
  <div class="d-flex align-items-center mb-0 me-2">
    <%= label_tag :end_date, "End Date", class: "form-label mb-0 form-input" %>
    <%= date_field_tag :end_date, params[:end_date], class: "form-control rounded-5" %>
  </div>
  <%= submit_tag "Search", name: nil, class: "btn btn-primary ms-2 rounded-4", id: "search-button" %>
<% end %>

app/views/cars/create.html.erb
<h1>Cars#create</h1>
<p>Find me in app/views/cars/create.html.erb</p>

app/views/cars/index.html.erb
<div class="container-fluid mt-2" data-controller="toggle">
  <div class="row">

    <%# Search and Switch %>
    <div id="search-form" class="col-12 d-flex justify-content-between align-items-center pb-2"> <!-- Added mb-3 for margin-bottom space under the switch -->
      <div class="col-4">
        <%= render partial: 'search' %>
      </div>
      <div class="d-flex align-items-center">
        <span class="me-2">See map</span> <!-- Text before the switch -->
        <label class="switch">
          <input type="checkbox" data-action="click->toggle#toggleMap">
          <span class="slider round"></span>
        </label>
        <span class="ms-2">See cars</span> <!-- Text after the switch -->
      </div>
    </div>

    <%# Cars %>
    <div id="cars-column" class="col-md-6" data-target="toggle.carsColumn">
      <div class="row"> <!-- This row will contain the grid of car cards -->
        <% @cars.where.not(user: current_user).each do |car| %> <!-- Loop over each car, that is not the user's own car -->
            <!-- Adjust the column size here for the desired number of cards per row, e.g., 'col-sm-6' for 2 cards per row on small screens and 'col-xl-4' for 3 cards per row on extra large screens -->
          <div class="col-sm-12 col-xl-6 mb-4">
            <%= render partial: 'car', locals: { car: car } %> <!-- Render the partial for each car -->
          </div>
        <% end %>
      </div>
    </div>

    <%# Map %>
    <div id="map-column" class="col-md-6" style="height: 100vh;" data-target="toggle.mapColumn"> <!-- This will take the other half -->
      <div style="width: 100%; height: 100%; border: 1px solid #ccc; border-radius: 15px; overflow: hidden;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        <!-- Your map will be here -->
      </div>
    </div>

  </div>
</div>

app/views/cars/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6 mb-3">
      <h1 class="text-center">Add your car</h1>
      <div style="width: 75%; hight: 30%; box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2); padding: 20px; margin: 0 auto;">
        <%= render "form", car: @car %>
      </div>
    </div>
  </div>
</div>

app/views/cars/user_cars.html.erb
<% @cars.each do |car| %>
  <li><%= car.model %></li>
<% end %>

app/views/layouts/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_importmap_tags %>

    <%# Fonts %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;800&display=swap" rel="stylesheet">

    <%# Flatpickr %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

    <%# Mapbox %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">

    <%# Mapbox Geocoder %>
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">

    <%# Turbo %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%# Favicon %>
    <%= favicon_link_tag asset_path("rentr_logo.png") %>
  </head>

  <body>
    <div id="page-container">
      <div id="content-wrap">
        <%= render 'devise/shared/navbar' %>
        <%= render 'layouts/flashes' %>
        <%= yield %>
    </div>
    <%= render 'pages/footer' %>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/_footer.html.erb
<footer class="bg-body-tertiary text-center footer">
  <div class="d-flex justify-content-end p1" >
    <span class="justify-content-center">&copy; 2023 Copyright</span>
      <div class="container p-1">
        <section class="">
          <div class="d-flex justify-content-center  align-items-center">
            <div class="px-2 ">
              <p class="">Created By</p>
            </div>
            <div class="px-2 d-flex">
              <a href="https://github.com/Ches-ctrl" target="_blank" rel="noopener noreferrer">
                <div class="rounded-circle overflow-hidden d-inline-block" style="width: 25px; height: 25px; background-color: #fff; margin-right: 3px;">
                  <img src="https://avatars.githubusercontent.com/u/65985457?v=4" class="w-100 h-100 rounded-circle" style="object-fit: cover;">
                </div>
              </a>
              <p>Charlie</p>
            </div>
            <div class="px-2 d-flex">
              <a href="https://github.com/obreil54" target="_blank" rel="noopener noreferrer">
                <div class="rounded-circle overflow-hidden d-inline-block" style="width: 25px; height: 25px; background-color: #fff; margin-right: 3px;">
                  <img src="https://avatars.githubusercontent.com/u/89271092?v=4" class="w-100 h-100 rounded-circle" style="object-fit: cover;">
                </div>
              </a>
              <p> Ilya</p>
            </div>
            <div class="px-2 d-flex">
              <a href="https://github.com/Direncan89" target="_blank" rel="noopener noreferrer">
                <div class="rounded-circle overflow-hidden d-inline-block" style="width: 25px; height: 25px; background-color: #fff; margin-right: 3px;">
                  <img src="https://avatars.githubusercontent.com/u/120759679?v=4" class="w-100 h-100 rounded-circle" style="object-fit: cover;">
                </div>
              </a>
              <p class=>Direncan</p>
            </div>
            <div class="px-2 d-flex">
              <a href="https://github.com/Debaerecharlotte" target="_blank" rel="noopener noreferrer">
                <div class="rounded-circle overflow-hidden d-inline-block" style="width: 25px; height: 25px; background-color: #fff; margin-right: 3px;">
                  <img src="https://avatars.githubusercontent.com/u/128391812?v=4" class="w-100 h-100 rounded-circle" style="object-fit: cover;">
                </div>
              </a>
              <p class=>Charlotte</p>
            </div>
          </div>
        </section>
      </div>
    <a class="text-body ml-2" href="https://github.com/Ches-ctrl/Rentr">Cheddar INC</a>
  </div>
</footer>

app/views/pages/home.html.erb
<div class="background" id="landing-page-background">
  <div class="container">
    <div class="row">
      <div class="col-sm-10 d-flex flex-column justify-content-center align-items-center mx-auto" style="height: 650px">
        <div id="punchline" class="d-flex flex-column align-items-center landing-page-container text-center ">
          <h1 class="display-1">Rent your next adventure </h1>
          <h2 class="display-4">Everything you need to rent a high-end electric vehicle</h2>
          <%= link_to "Start your journey", cars_path, class: "btn-lg mt-4 text-center" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1>Welcome <%= current_user.first_name %> <%= current_user.last_name %>!</h1>
<div id="profile-details">
  <% if current_user.photo.key %>
    <%= cl_image_tag current_user.photo.key, class: "avatar-large" %>
  <% else %>
    <%= image_tag('avatar_default.png', class: "avatar-large") %>
  <% end %>
  <div id="profile-info">
    <p>Your email: <%= current_user.email %></p>
    <% if current_user.license_number.length >= 1 %>
      <p>Your driving licence number: <%= current_user.license_number %></p>
    <% end %>
    <p><%= link_to raw("<i class='fa-solid fa-pencil'></i> Edit Your Details"), edit_user_registration_path(current_user)%></p>
  </div>
</div>
<div id="profile-items">
    <div class="profile-items-container">
      <div class="profile-items-header">
        <h4><%= link_to "Your Cars", user_cars_cars_path %></h4>
        <h4><%= link_to raw("<i class='fa-solid fa-plus'></i> Add Car"), new_car_path %></h4>
      </div>
      <% if current_user.cars.any? %>
        <div class="container-fluid mt-2">
          <div class="row">
            <% current_user.cars.each do |car| %>
              <div class="col-md-3 mb-4">
                <div class="link-container">
                  <%= link_to car_path(car) do %>
                  <div class="card">
                    <% carousel_id = "carousel#{car.id}Indicators" %>
                    <div class="card-image">
                      <div id="<%= carousel_id %>" class="carousel slide">
                        <div class="carousel-indicators">
                          <% car.photos.each_with_index do |photo, index| %>
                            <button type="button" data-bs-target="#<%= carousel_id %>" data-bs-slide-to="<%= index %>" class="<%= 'active' if index.zero? %>" aria-label="Slide <%= index + 1 %>"></button>
                          <% end %>
                        </div>
                        <div class="carousel-inner">
                          <% car.photos.each_with_index do |photo, index| %>
                            <div class="carousel-item <%= 'active' if index.zero? %>">
                              <%= image_tag(photo, class: 'd-block w-100', alt: "#{car.brand} #{car.model}") %>
                            </div>
                          <% end %>
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#<%= carousel_id %>" data-bs-slide="prev">
                          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                          <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#<%= carousel_id %>" data-bs-slide="next">
                          <span class="carousel-control-next-icon" aria-hidden="true"></span>
                          <span class="visually-hidden">Next</span>
                        </button>
                      </div>
                    </div>
                    <div class="card-body">
                      <div class="card-title d-flex">
                        <h2 class="card-title 1 me-2"><%= car.brand %></h2>
                        <h2><%= car.model %></h2>
                      </div>
                      <div class="card-details-1">
                        <p class="card-text"> <i class="fa-solid fa-gears"></i> <%= car.transmission %></p>
                        <p class="card-text"> <i class="fa-solid fa-location-dot"></i> <%= car.location %></p>
                      </div>
                      <div class="d-flex justify-content-end">
                        <p class="card-price"> £<%= car.day_rate %>/day</p>
                      </div>
                    </div>
                  </div>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
      </div>
      <div class="profile-items-container">
    <div class="profile-items-header">
      <h4><%= link_to "Your Bookings", user_bookings_bookings_path %></h4>
      <h4><%= link_to raw("<i class='fa-solid fa-plus'></i> Find A Car And Book Today!"), cars_path %></h4>
    </div>
    <% if current_user.bookings.any? %>
        <div class="container-fluid mt-2">
          <div class="row">
            <% current_user.bookings.each do |booking| %>
              <div class="col-md-3 mb-4">
                <div class="link-container">
                  <%= link_to car_path(booking.car) do %>
                  <div class="card">
                    <% carousel_id = "carousel#{booking.id}Indicators" %>
                    <div class="card-image">
                      <div id="<%= carousel_id %>" class="carousel slide">
                        <div class="carousel-indicators">
                          <% booking.car.photos.each_with_index do |photo, index| %>
                            <button type="button" data-bs-target="#<%= carousel_id %>" data-bs-slide-to="<%= index %>" class="<%= 'active' if index.zero? %>" aria-label="Slide <%= index + 1 %>"></button>
                          <% end %>
                        </div>
                        <div class="carousel-inner">
                          <% booking.car.photos.each_with_index do |photo, index| %>
                            <div class="carousel-item <%= 'active' if index.zero? %>">
                              <%= image_tag(photo, class: 'd-block w-100', alt: "#{booking.car.brand} #{booking.car.model}") %>
                            </div>
                          <% end %>
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#<%= carousel_id %>" data-bs-slide="prev">
                          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                          <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#<%= carousel_id %>" data-bs-slide="next">
                          <span class="carousel-control-next-icon" aria-hidden="true"></span>
                          <span class="visually-hidden">Next</span>
                        </button>
                      </div>
                    </div>
                <div class="card-body">
                  <div class="card-title d-flex">
                    <h5 class="card-title 1 me-2"><%= booking.start_date.strftime('%b %d %Y') %></h5>
                    <h5> - <%= booking.end_date.strftime('%b %d %Y') %></h5>
                  </div>
                  <div class="card-details-1">
                    <p class="card-text"> <i class="fa-solid fa-car"></i></i> <%= booking.car.brand %> <%= booking.car.model %></p>
                    <p class="card-price"> £<%= booking.car.day_rate.round() %>/day</p>
                  </div>
                  <div class="d-flex justify-content-end">
                    <p class="card-text"> <i class="fa-solid fa-money-bill"></i> Total £<%= ((booking.end_date - booking.start_date) * booking.car.day_rate).round(2)%></p>
                  </div>
                </div>
              </div>
             <% end %>
            </div>
        </div>
      <% end %>
      </div>
    <% end %>
  </div>
</div>